/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.DonorEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import Business.Role.DonorRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userInterface.AdminRole.AdminWorkAreaPanel;
import userInterface.DonorRole.DonorWorkAreaPanel;

/**
 *
 * @author deepankkhurana
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    EcoSystem system;
    DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    UserAccount userAccount;

  public MainJFrame() {
        initComponents();
        try {
            String imageFilePath = "./AmericareLogo.jpg";
            ImageIcon icon = new ImageIcon(imageFilePath);
            Image image = icon.getImage().getScaledInstance(300, 125, Image.SCALE_SMOOTH);
            LogoLabel.setIcon(new ImageIcon(image));
            LogoLabel.setText("");
            String imageFilePath1 = "./JoyOfDonation.jpg";
            ImageIcon icon1 = new ImageIcon(imageFilePath1);
            Image image1 = icon1.getImage().getScaledInstance(950, 250, Image.SCALE_SMOOTH);
            JoyLabel.setIcon(new ImageIcon(image1));
            JoyLabel.setText("");
            
            String imageFilePath2 = "./donationBtn.jpg";
            ImageIcon icon2 = new ImageIcon(imageFilePath2);
            Image image2 = icon2.getImage().getScaledInstance(250, 100, Image.SCALE_SMOOTH);
            donateLabel.setIcon(new ImageIcon(image2));
            donateLabel.setText("");
            system = dB4OUtil.retrieveSystem();
            signUpBtn.setEnabled(true);
            userAccount = new UserAccount();
        }
        catch(NullPointerException ne){
           JOptionPane.showMessageDialog(null, "Error : "+ne.getMessage()); 
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : "+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        loginMenuJPanel = new javax.swing.JPanel();
        userNameLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        signUpBtn = new javax.swing.JButton();
        passwordTextField = new javax.swing.JPasswordField();
        LogoLabel = new javax.swing.JLabel();
        LogOut = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        JoyLabel = new javax.swing.JLabel();
        donateLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setDividerLocation(170);
        splitPane.setDividerSize(4);
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPane.setMinimumSize(new java.awt.Dimension(95, 314));
        splitPane.setPreferredSize(new java.awt.Dimension(1450, 487));

        loginMenuJPanel.setBackground(new java.awt.Color(0, 102, 102));
        loginMenuJPanel.setPreferredSize(new java.awt.Dimension(1680, 170));

        userNameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        userNameLabel.setForeground(java.awt.Color.white);
        userNameLabel.setText("Username");

        passLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        passLabel.setForeground(java.awt.Color.white);
        passLabel.setText("Password");

        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Please Enter Your Login Credentials");

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        jLabel2.setBackground(java.awt.Color.red);
        jLabel2.setFont(new java.awt.Font("Noteworthy", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Welcome To AMERICARE");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("SHOW YOUR CARE WITH SHARE!!");

        signUpBtn.setText("Donate Now");
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });

        LogoLabel.setText("LOGO");
        LogoLabel.setPreferredSize(new java.awt.Dimension(31, 16));

        LogOut.setText("LogOut");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginMenuJPanelLayout = new javax.swing.GroupLayout(loginMenuJPanel);
        loginMenuJPanel.setLayout(loginMenuJPanelLayout);
        loginMenuJPanelLayout.setHorizontalGroup(
            loginMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginMenuJPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(loginMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginMenuJPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginMenuJPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addGroup(loginMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginMenuJPanelLayout.createSequentialGroup()
                        .addGroup(loginMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userNameLabel)
                            .addComponent(passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(loginMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginMenuJPanelLayout.createSequentialGroup()
                        .addComponent(signUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LogOut)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginMenuJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(75, 75, 75))))
        );
        loginMenuJPanelLayout.setVerticalGroup(
            loginMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginMenuJPanelLayout.createSequentialGroup()
                .addGroup(loginMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginMenuJPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(loginMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(loginMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(loginMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LogOut)
                            .addComponent(signUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loginMenuJPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginMenuJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        splitPane.setTopComponent(loginMenuJPanel);

        container.setBackground(new java.awt.Color(0, 140, 190));
        container.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(0, 140, 190));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("INSTRUCTION FOR NEW USERS");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("1) Please Enter All the Details Carefully.");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("2) Please Provide a Valid Email ID and Mobile Number.");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("3) Please choose the type of donation carefully before scheduling a pickup.");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("4) Donation will be picked up from your place within 2 business days. ");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("5) Incase of unavailability at chosen time, please cancel the pickup at the earliest.");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("6) Blood and Organ Donation will be accepted only after approval from Doctor.");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("7) In case of cloth donation please make sure clothes are not torn and are in good condition.");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("8) Keep the food well refrigerated and do not donate stale food.");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("9) You will receieve Email from our end to keep you informed about your donation status.");

        JoyLabel.setText("JoyLabel");

        donateLabel.setText("donateLabel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JoyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 927, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(donateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JoyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(donateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        container.add(jPanel1, "card2");

        splitPane.setRightComponent(container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1543, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1073, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        
   signUpBtn.setEnabled(false);
        if (userNameTextField.getText().isEmpty() || passwordTextField.getPassword().length == 0) {
            JOptionPane.showMessageDialog(null, "Please enter username and password to login");
            return;
        }
        try {
            // Get user name
            String userName = userNameTextField.getText();
            // Get Password
            char[] passwordCharArray = passwordTextField.getPassword();
            String password = String.valueOf(passwordCharArray);

            //Step1: Check in the system admin user account directory if you have the user
            userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);

            Network inNetwork = null;
            Enterprise inEnterprise = null;
            Organization inOrganization = null;

            if (userAccount == null) {
                //Step 2: Go inside each network and check each enterprise
                for (Network network : system.getNetworkList()) {
                    //Step 2.a: check against each enterprise
                    for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                        userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                        if (userAccount == null) {
                            //Step 3:check against each organization for each enterprise
                            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                                userAccount = organization.getUserAccountDirectory().authenticateUser(userName, password);
                                if (userAccount != null) {
                                    inNetwork = network;
                                    inEnterprise = enterprise;
                                    inOrganization = organization;
                                    break;
                                }
                            }

                        } else {
                            inEnterprise = enterprise;
                            break;
                        }
                        if (inOrganization != null) {
                            break;
                        }
                    }
                    if (inEnterprise != null) {
                        break;
                    }
                }
            }

            if (userAccount == null) {
                JOptionPane.showMessageDialog(null, "Invalid credentials");
                return;
            } else {
                CardLayout layout = (CardLayout) container.getLayout();
                container.add("workArea", userAccount.getRole().createWorkArea(container, userAccount, inOrganization, inEnterprise, system, inNetwork));
                layout.next(container);
            }

            loginBtn.setEnabled(false);
            LogOut.setEnabled(true);
            userNameTextField.setEnabled(false);
            passwordTextField.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Something went wrong..loginBtnActionPerformed");
        }       
        
    }//GEN-LAST:event_loginBtnActionPerformed

    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
        
        
//        CardLayout layout = (CardLayout) container.getLayout();
//        //container.add("workArea", userAccount.getRole().createWorkArea(container, userAccount, inOrganization, inEnterprise, system, inNetwork));
//        layout.next(container);
//        
//        
//        DonorWorkAreaPanel donorPanel= new DonorWorkAreaPanel(container);
//       Container.add("DonorWorkPanel", donorPanel);
//       CardLayout layout=(CardLayout)Container.getLayout();
//       layout.next(Container);
//        
//                try {
//                     DonorRole donorRole = new DonorRole() {
//                         @Override
//                         public JPanel createWorkArea(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Ecosystem business, Network network) {
//                             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//                         }
//                     };
//            DonorOrganization donorOrg = new DonorOrganization();
//            Enterprise inEnterprise = new DonorEnterprise("Donor");
//            Network network = new Network();
//
//          //  CardLayout layout = (CardLayout) Container.getLayout();
//            Container.add("workArea", donorRole.createWorkArea(Container, userAccount, donorOrg, inEnterprise, system, network));
//            layout.next(Container);
//            signUpBtn.setEnabled(false);
//        } catch(NullPointerException ne){
//           JOptionPane.showMessageDialog(null, "Error : "+ne.getMessage()); 
//        } 
//        catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Error : "+e.getMessage());
//        }
//        
  try {
            DonorRole donorRole = new DonorRole();
            DonorOrganization donorOrg = new DonorOrganization();
            Enterprise inEnterprise = new DonorEnterprise("Donor");
            Network network = new Network();

            CardLayout layout = (CardLayout) container.getLayout();
            container.add("workArea", donorRole.createWorkArea(container, userAccount, donorOrg, inEnterprise, system, network));
            layout.next(container);
            signUpBtn.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }//GEN-LAST:event_signUpBtnActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
          LogOut.setEnabled(false);
        userNameTextField.setEnabled(true);
        passwordTextField.setEnabled(true);
        loginBtn.setEnabled(true);

        userNameTextField.setText("");
        passwordTextField.setText("");

        container.removeAll();
        try {
            JPanel blankJP = new JPanel();
            blankJP.setBackground(new Color(179, 205, 224));
            container.add("blank", blankJP);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.next(container);
            dB4OUtil.storeSystem(system);
            signUpBtn.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Something went wrong..LogOutActionPerformed");
        }
    }//GEN-LAST:event_LogOutActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JoyLabel;
    private javax.swing.JButton LogOut;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JPanel container;
    private javax.swing.JLabel donateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginMenuJPanel;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JButton signUpBtn;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
