/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.WarehouseDistributionRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Inventory.InventoryDetails;
import Business.Inventory.InventoryDirectory;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.WarehouseDistributionOrganization;
import Business.UserAccount.UserAccount;
import Business.Workqueue.DistributeDonationWorkRequest;
import Business.Workqueue.WorkRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author deepankkhurana
*/

    /**
     * Creates new form WarehouesDistributionRoleWArea
     */
public class WarehouesDistributionRoleWArea extends javax.swing.JPanel {

    /**
     * Creates new form WarehouseDistributionRoleWorkArea
     */
    private final JPanel userProcessContainer;
    private final WarehouseDistributionOrganization organization;
    private final Enterprise enterprise;
    private final UserAccount userAccount;
    private final ArrayList<Organization> orgs;
    private final EcoSystem system;
    private final Network network;
    
    public WarehouesDistributionRoleWArea(JPanel userProcessContainer, UserAccount account, WarehouseDistributionOrganization organization, Enterprise enterprise, EcoSystem system, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.orgs = new ArrayList<>();
        this.system = system;
        this.network = network;
        try{
        valueLbl.setText(enterprise.getName());
        networkLbl.setText(network.getName());
        
        for(Network n : system.getNetworkList()){
            if(n.getName().equals(network.getName())){
                for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                    for(Organization o : e.getOrganizationDirectory().getOrganizationList()){
                        orgs.add(o);
                    }
                } 
            }
        }
        
        populateDistributionRequestJTable();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }
    
    public void populateDistributionRequestJTable(){
        try{
        DefaultTableModel model = (DefaultTableModel)distributionWorkRequestJTable.getModel();
        model.setRowCount(0);
        for(Organization org : orgs){
           if(org instanceof WarehouseDistributionOrganization) {
            for (DistributeDonationWorkRequest request : org.getWorkQueue().getDistributionWorkRequestList()){
                Object[] row = new Object[5];
                row[0] = request;
                row[1] = request.getLocation();
                row[2] = request.getSender() == null ? null : request.getSender().getEmployee().getEmpName();
                row[3] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getEmpName();
                row[4] = request.getStatus();
                model.addRow(row);
                } 
            }
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }               

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        valueLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        networkLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        distributionWorkRequestJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(0, 140, 190));

        jLabel2.setText("<Enterprise>");

        valueLbl.setText("<enterprise name>");

        jLabel5.setText("Network");

        networkLbl.setText("<network name>");

        distributionWorkRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Donation Type", "Location", "Requested By", "Accepted by", "Status"
            }
        ));
        jScrollPane1.setViewportView(distributionWorkRequestJTable);

        jLabel1.setText("Accept Distribution  Request");

        jLabel3.setText("Update Distribution Status");

        jButton1.setText("Accept");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2)
                        .addGap(72, 72, 72)
                        .addComponent(valueLbl)
                        .addGap(249, 249, 249)
                        .addComponent(jLabel5)
                        .addGap(71, 71, 71)
                        .addComponent(networkLbl))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(valueLbl)
                    .addComponent(jLabel5)
                    .addComponent(networkLbl))
                .addGap(71, 71, 71)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton2))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        add(jPanel2, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        int selectedRow = distributionWorkRequestJTable.getSelectedRow();
        String acceptedBy = String.valueOf(distributionWorkRequestJTable.getValueAt(selectedRow, 3));
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a distribution request to accept.");
        }
        else {
            if(acceptedBy.equals("null")){
                WorkRequest request = (WorkRequest)distributionWorkRequestJTable.getValueAt(selectedRow, 0);
                request.setReceiver(userAccount);
                request.setStatus("Pending");
                populateDistributionRequestJTable();
            }
            else JOptionPane.showMessageDialog(null, "Already accepted.");
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
        int selectedRow = distributionWorkRequestJTable.getSelectedRow();
        if (selectedRow >= 0){
            DistributeDonationWorkRequest request = (DistributeDonationWorkRequest)distributionWorkRequestJTable.getValueAt(selectedRow, 0);
            String status = String.valueOf(distributionWorkRequestJTable.getValueAt(selectedRow, 4));
            String acceptedBy = String.valueOf(distributionWorkRequestJTable.getValueAt(selectedRow, 3));
            if(status.equals("Pending") && acceptedBy.equals(userAccount.getEmployee().getEmpName())){
               WorkRequest workRequest = (WorkRequest)distributionWorkRequestJTable.getValueAt(selectedRow, 0);
               request.setStatus("Distributed");
               workRequest.setStatus("Distributed");
               populateDistributionRequestJTable();
               int id = request.getDonationId();
               InventoryDirectory inventoryList = new InventoryDirectory();
               for(InventoryDetails inventory : inventoryList.getInventory()){
                   if(id==inventory.getDonationId()) inventoryList.getInventory().remove(inventory);
               }
            }
            else JOptionPane.showMessageDialog(null, "Please select a 'Pending' distribution request accepted by you to update.");
        }
        else JOptionPane.showMessageDialog(null, "Please select a collection request to update.");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable distributionWorkRequestJTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel networkLbl;
    private javax.swing.JLabel valueLbl;
    // End of variables declaration//GEN-END:variables
    }

