/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.LabAssistantRole;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.Workqueue.LabWorkRequest;
import Business.Workqueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sahebsingh
 */
public class ProcessWorkRequestPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessWorkRequestPanel
     */
    
   private final JPanel userProcessContainer;
    private final UserAccount account;
    private final LabWorkRequest request;
    
    public ProcessWorkRequestPanel(JPanel userProcessContainer, UserAccount account, LabWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.request = request;
        try{
        testResultComboBox.removeAllItems();
        testResultComboBox.addItem("Optimal");
        testResultComboBox.addItem("Not Optimal");
        testTypeLbl.setText(request.getTestType());
        
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        testTypeLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        testResultComboBox = new javax.swing.JComboBox<>();
        completeBtn = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(0, 140, 190));

        jLabel1.setText("Test type");

        jLabel3.setText("Test Result");

        testResultComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        testResultComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testResultComboBoxActionPerformed(evt);
            }
        });

        completeBtn.setText("Complete");
        completeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeBtnActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(testResultComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(completeBtn))
                    .addComponent(testTypeLbl))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testTypeLbl)
                    .addComponent(jLabel1))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(testResultComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(completeBtn))
                .addGap(47, 47, 47)
                .addComponent(btnBack)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void testResultComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testResultComboBoxActionPerformed
        // TODO add your handling code here:
         
        try{
        WorkRequest r = (WorkRequest)request;
        r.setMessage(String.valueOf(testResultComboBox.getSelectedItem()));
        r.setStatus("Complete");
        JOptionPane.showMessageDialog(null, "Completed successfully.");
        
        //Send Email to donor
        String message="";
  //      String to = request.getDonorEmailId();
        String subject = "Donation verdict";
        switch (String.valueOf(testResultComboBox.getSelectedItem())) {
            case "Optimal":
                message =  "Thank you! Your donation is accepted. We appreciate you endeavor to support a needy!";
                break;
            case "Not Optimal":
                message =  "We appreciate you endeavor to support a needy. We are sorry, but we found that your donation doesn't meet the required medical conditions to be optimal. Please reach out to us again in near future.";
                break;
        }
        String user = "aeddemogss@gmail.com";
        String pass = "aed_gss123";

       // SendEmail.send(to,subject, message, user, pass);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
        
    }//GEN-LAST:event_testResultComboBoxActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
            try{
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LabAssistantWorkAreaPanel jp = (LabAssistantWorkAreaPanel)component;
        jp.populateWorkRequestJTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void completeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeBtnActionPerformed
        // TODO add your handling code here:
        
       if(testResultComboBox.getSelectedIndex()<0){
                        JOptionPane.showMessageDialog(null, "Please select blood type");
                    }
                    else {
       
       }
        
    }//GEN-LAST:event_completeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton completeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> testResultComboBox;
    private javax.swing.JLabel testTypeLbl;
    // End of variables declaration//GEN-END:variables
}
