/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.DonorRole;

import Business.Donor.Donor;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.BloodBankOrganization;
import Business.Organization.ClothesNGOOrganization;
import Business.Organization.DonorOrganization;
import Business.Organization.FoodNGOOrganization;
import Business.Organization.OrganBankOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Workqueue.AcceptDonationWorkRequest;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rashikamoza
 */
public class DonorWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonorWorkAreaPanel
     */
    private final JPanel userProcessContainer;
    private final DonorOrganization organization;
    private final Enterprise enterprise;
    private final UserAccount userAccount;
    private final EcoSystem system;
    
    public DonorWorkAreaPanel(JPanel userProcessContainer, UserAccount account, DonorOrganization organization, Enterprise enterprise, EcoSystem system, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.system = system;
        
        //valueLabel.setText(enterprise.getName());
        try{
            loadNetworksComboBox();
            loadDonationTypeComboBox();

            donationTypeComboBox.setSelectedIndex(-1);
            networkComboBox.setSelectedIndex(-1);

            donationTypeComboBox.setEnabled(false);
            btnYes.setEnabled(false);
            btnNo.setEnabled(false);
            btnSubmit.setEnabled(false);
            lblBloodType.setVisible(false);
            bloodTypeComboBox.setVisible(false);
            lblOrganType.setVisible(false);
            organTypeComboBox.setVisible(false);

            nameTxtBox.setEnabled(false);
            addressTxtArea.setEnabled(false);
            emailIdTxtBox.setEnabled(false);
            contactTxtBox.setEnabled(false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }
    
    public void loadNetworksComboBox(){
        try{
            networkComboBox.removeAllItems();
            for (Network network : system.getNetworkList()) {
                networkComboBox.addItem(network);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }
    
    public  void loadDonationTypeComboBox(){
        try{
            donationTypeComboBox.removeAllItems();
            String net = String.valueOf(networkComboBox.getSelectedItem());
            for(Network n : system.getNetworkList()){
                if(n.getName().equals(net)){
                    for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                        for(Organization o: e.getOrganizationDirectory().getOrganizationList()){
                            if((o instanceof FoodNGOOrganization)||(o instanceof ClothesNGOOrganization)||
                                    (o instanceof BloodBankOrganization)||(o instanceof OrganBankOrganization)){
                                donationTypeComboBox.addItem(o);
                            }
                        }
                    }
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        networkComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        nameTxtBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailIdTxtBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        contactTxtBox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTxtArea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        lblOrganType = new javax.swing.JLabel();
        lblBloodType = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        donationTypeComboBox = new javax.swing.JComboBox<>();
        bloodTypeComboBox = new javax.swing.JComboBox<>();
        organTypeComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btnYes = new javax.swing.JButton();
        btnNo = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(0, 140, 190));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("\"NO ONE IS USELESS IN THIS WORLD WHO LIGHTENS THE BURDENS OF ANOTHER\"");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Choose your network");

        networkComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Name");

        jLabel4.setText("Email ID");

        emailIdTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIdTxtBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Full Address");

        jLabel6.setText("Conatct No.");

        addressTxtArea.setColumns(20);
        addressTxtArea.setRows(5);
        jScrollPane1.setViewportView(addressTxtArea);

        jLabel7.setText("Donation to*");

        lblOrganType.setText("Organ Type*");

        lblBloodType.setText("Blood Type*");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        donationTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        donationTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donationTypeComboBoxActionPerformed(evt);
            }
        });

        bloodTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bloodTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodTypeComboBoxActionPerformed(evt);
            }
        });

        organTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("Do you want to add more?");

        btnYes.setText("Yes");
        btnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesActionPerformed(evt);
            }
        });

        btnNo.setText("No");
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(lblBloodType)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnAdd)
                                        .addComponent(jLabel7)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel10)
                                        .addGap(51, 51, 51)
                                        .addComponent(btnYes)
                                        .addGap(34, 34, 34)
                                        .addComponent(btnNo)
                                        .addGap(82, 82, 82)
                                        .addComponent(btnSubmit))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bloodTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(networkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(nameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(donationTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(78, 78, 78)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel6)
                                                    .addComponent(lblOrganType))
                                                .addGap(86, 86, 86)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(emailIdTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(contactTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(organTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(btnBack)))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(networkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(emailIdTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(contactTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblOrganType)
                    .addComponent(donationTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(organTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBloodType)
                    .addComponent(bloodTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(jLabel10)
                    .addComponent(btnYes)
                    .addComponent(btnNo)
                    .addComponent(btnSubmit))
                .addGap(55, 55, 55)
                .addComponent(btnBack)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void emailIdTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIdTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailIdTxtBoxActionPerformed

    private void bloodTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodTypeComboBoxActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
         String name = nameTxtBox.getText();
        String email = emailIdTxtBox.getText();
        String contact = contactTxtBox.getText();
        String address = addressTxtArea.getText();
        try{
        Organization donateAt = (Organization)donationTypeComboBox.getSelectedItem();
        String network = String.valueOf(networkComboBox.getSelectedItem());
        String donation = "";
        
        //checking if any field is left blank
        if(networkComboBox.getSelectedIndex() < 0 || donationTypeComboBox.getSelectedIndex() < 0 || name.isEmpty() || email.isEmpty() || contact.isEmpty() || address.isEmpty()){
            JOptionPane.showMessageDialog(null,"All the fields are compulsory");
            return;
        }
        
        //assigning proper value to donation depending on value selected from donationtype dropdown
        if(donateAt instanceof BloodBankOrganization) donation = "Blood";
        else if(donateAt instanceof OrganBankOrganization) donation = "Organ";
        else if(donateAt instanceof FoodNGOOrganization) donation = "Food";
        else if(donateAt instanceof ClothesNGOOrganization) donation = "Clothes";
        
        if(name.matches("^[a-zA-Z]+$") && email.matches("^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$")
                && contact.matches("^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}$")){
            switch (donation) {
                case "Blood":
                    if(bloodTypeComboBox.getSelectedIndex()<0){
                        JOptionPane.showMessageDialog(null, "Please select blood type");
                    }
                    else {
                        String bloodType = String.valueOf(bloodTypeComboBox.getSelectedItem());
                        for(Network n : system.getNetworkList()){
                            if (network.equals(n.getName())){
                                for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                                    for(Organization o : e.getOrganizationDirectory().getOrganizationList()){
                                        if(o instanceof BloodBankOrganization){
                                            Donor donor = organization.getDonorDir().createDonor(name, email, contact, address, donation, bloodType, " ",network);
                                            btnYes.setEnabled(true);
                                            btnNo.setEnabled(true);
                                            btnAdd.setEnabled(false);
                                            donationTypeComboBox.setSelectedIndex(-1);
                                            AcceptDonationWorkRequest request = new AcceptDonationWorkRequest();
                                            request.setDonor(donor);
                                            o.getWorkQueue().getDonationWorkRequestList().add(request);
                                            JOptionPane.showMessageDialog(null,"Added successfully");
                                            break;
                                        }
                                    }
                                }
                            }
                        }
                    }   break;
                case "Organ":
                    if(organTypeComboBox.getSelectedIndex()<0){
                        JOptionPane.showMessageDialog(null, "Please select organ type");
                    }
                    else {
                        String organType = String.valueOf(organTypeComboBox.getSelectedItem());
                        for(Network n : system.getNetworkList()){
                            if (networkComboBox.getSelectedItem().equals(n)){
                                for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                                    for(Organization o : e.getOrganizationDirectory().getOrganizationList()){
                                        if(o instanceof OrganBankOrganization){
                                            Donor donor = organization.getDonorDir().createDonor(name, email, contact, address, donation, " ", organType, network);
                                            btnYes.setEnabled(true);
                                            btnNo.setEnabled(true);
                                            btnAdd.setEnabled(false);
                                            donationTypeComboBox.setSelectedIndex(-1);
                                            AcceptDonationWorkRequest request = new AcceptDonationWorkRequest();
                                            request.setDonor(donor);
                                            o.getWorkQueue().getDonationWorkRequestList().add(request);
                                            JOptionPane.showMessageDialog(null,"Added successfully");
                                            break;
                                        }
                                    }
                                }
                            }
                        }
                    }   break;
                default:
                    btnYes.setEnabled(true);
                    btnNo.setEnabled(true);
                    btnAdd.setEnabled(false);
                    lblBloodType.setVisible(false);
                    bloodTypeComboBox.setVisible(false);
                    lblOrganType.setVisible(false);
                    organTypeComboBox.setVisible(false);
                    for(Network n : system.getNetworkList()){
                        if (networkComboBox.getSelectedItem().equals(n)){
                            for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                                for(Organization o: e.getOrganizationDirectory().getOrganizationList()){
                                    if((o instanceof FoodNGOOrganization) && (donationTypeComboBox.getSelectedItem() instanceof FoodNGOOrganization)){
                                        Donor donor = organization.getDonorDir().createDonor(name, email, contact, address, donation, " ", " ",network);
                                        AcceptDonationWorkRequest request = new AcceptDonationWorkRequest();
                                        request.setDonor(donor);
                                        o.getWorkQueue().getDonationWorkRequestList().add(request);
                                        JOptionPane.showMessageDialog(null,"Added successfully");
                                        donationTypeComboBox.setSelectedIndex(-1);
                                        break;
                                    }
                                    else if((o instanceof ClothesNGOOrganization) && (donationTypeComboBox.getSelectedItem() instanceof ClothesNGOOrganization)){
                                        Donor donor = organization.getDonorDir().createDonor(name, email, contact, address, donation, " ", " ",network);
                                        AcceptDonationWorkRequest request = new AcceptDonationWorkRequest();
                                        request.setDonor(donor);
                                        o.getWorkQueue().getDonationWorkRequestList().add(request);
                                        JOptionPane.showMessageDialog(null,"Added successfully");
                                        break;
                                    }
                                }
                            }
                        }
                    }
                    break;
                }
            }
        else {
            JOptionPane.showMessageDialog(null,"Please ensure that the entered details are valid. E.g. Name should be alphabets only and contact number should be digits only.");
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesActionPerformed
        // TODO add your handling code here:
        btnAdd.setEnabled(true);
        donationTypeComboBox.setSelectedIndex(-1);
    }//GEN-LAST:event_btnYesActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        // TODO add your handling code here:
        btnSubmit.setEnabled(true);
        btnYes.setEnabled(true);
    }//GEN-LAST:event_btnNoActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
          JOptionPane.showMessageDialog(null,"Donation request submitted successfully");
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void donationTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donationTypeComboBoxActionPerformed
        // TODO add your handling code here:
        try{
        Organization donateAt = (Organization)donationTypeComboBox.getSelectedItem();
        String donation = "";
        if(donateAt instanceof BloodBankOrganization) donation = "Blood";
        else if(donateAt instanceof OrganBankOrganization) donation = "Organ";
        else if(donateAt instanceof FoodNGOOrganization) donation = "Food";
        else if(donateAt instanceof ClothesNGOOrganization) donation = "Clothes";
        
        switch (donation) {
            case "Blood":
                lblBloodType.setVisible(true);
                bloodTypeComboBox.setVisible(true);
                bloodTypeComboBox.removeAllItems();  // to load type of blood combo box
                bloodTypeComboBox.addItem("O+");
                bloodTypeComboBox.addItem("B+");
                bloodTypeComboBox.addItem("AB+");
                bloodTypeComboBox.addItem("A+");
                bloodTypeComboBox.addItem("O-");
                bloodTypeComboBox.addItem("B-");
                bloodTypeComboBox.addItem("AB-");
                bloodTypeComboBox.addItem("A-");
                bloodTypeComboBox.setSelectedIndex(-1);
                lblOrganType.setVisible(false);
                organTypeComboBox.setVisible(false);
                break;
            case "Organ":
                lblOrganType.setVisible(true);
                organTypeComboBox.setVisible(true);
                organTypeComboBox.removeAllItems();  // to load type of organ combo box
                organTypeComboBox.addItem("Kidney");
                organTypeComboBox.addItem("Eye");
                bloodTypeComboBox.setSelectedIndex(-1);
                lblBloodType.setVisible(false);
                bloodTypeComboBox.setVisible(false);
                break;
            default:
                lblBloodType.setVisible(false);
                bloodTypeComboBox.setVisible(false);
                lblOrganType.setVisible(false);
                organTypeComboBox.setVisible(false);
                break;
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }//GEN-LAST:event_donationTypeComboBoxActionPerformed

    private void networkComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkComboBoxActionPerformed
        // TODO add your handling code here:
              try{
        donationTypeComboBox.setEnabled(true);
        loadDonationTypeComboBox();
        donationTypeComboBox.setSelectedIndex(-1);
        nameTxtBox.setEnabled(true);
        addressTxtArea.setEnabled(true);
        emailIdTxtBox.setEnabled(true);
        contactTxtBox.setEnabled(true);
        lblBloodType.setVisible(false);
        bloodTypeComboBox.setVisible(false);
        lblOrganType.setVisible(false);
        organTypeComboBox.setVisible(false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }//GEN-LAST:event_networkComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressTxtArea;
    private javax.swing.JComboBox<Object> bloodTypeComboBox;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnYes;
    private javax.swing.JTextField contactTxtBox;
    private javax.swing.JComboBox<Object> donationTypeComboBox;
    private javax.swing.JTextField emailIdTxtBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblOrganType;
    private javax.swing.JTextField nameTxtBox;
    private javax.swing.JComboBox<Object> networkComboBox;
    private javax.swing.JComboBox<Object> organTypeComboBox;
    // End of variables declaration//GEN-END:variables
}
